<?php

declare(strict_types=1);

namespace App\Platforms\Clinical\Application\CommandHandler;

use App\Platforms\Clinical\Application\Command\ApproveClinicalContribution;
use App\Platforms\Clinical\Application\Port\ClinicalContributionRepositoryPort;
use App\Platforms\Clinical\Application\Port\DomainEventCollectorPort;

/**
 * Command Handler — UC-003: Approve Clinical Contribution.
 *
 * Single responsibility: execute the Approve use case within exactly one transaction
 * boundary owned by the Application Runtime (SA-007 §6.2, SA-005 D-003).
 *
 * Execution sequence (RVS-001 §10 ApproveClinicalContributionHandler):
 *  1. Runtime opens transaction.
 *  2. Handler retrieves ClinicalContribution via repository.retrieve().
 *  3. Handler calls aggregate.approve(approvingPractitionerId, approvedAt).
 *  4. Aggregate enforces BI-005 (status must be Validated) — throws if violated.
 *  5. Aggregate enforces BI-007 (approver ≠ contributor) — throws if violated.
 *  6. Aggregate records ClinicalContributionApproved and marks contribution immutable.
 *  7. Handler calls repository.persist() — updated aggregate state written within transaction.
 *  8. Handler calls eventCollector.collect() — events held for post-commit publication.
 *  9. Runtime commits transaction.
 * 10. Infrastructure publishes ClinicalContributionApproved post-commit (PR-004).
 *
 * WHY the Handler does not check BI-005 or BI-007 before calling approve():
 * Business invariant enforcement belongs exclusively to the Aggregate (PR-002 D-017).
 * A Handler that checked "is this contribution Validated?" before calling approve()
 * would be duplicating domain logic — and the check could become stale if the invariant
 * evolves. The Aggregate is the sole authority. The Handler trusts it and propagates exceptions.
 *
 * WHY approvedAt is carried in the Command rather than generated by the Handler:
 * The approval timestamp is a caller-supplied business input — the moment the Approving
 * Practitioner formally endorsed the contribution. This may differ from the Handler's
 * wall-clock if the command is queued. The caller controls the approval timestamp;
 * the Handler records it faithfully without substituting its own clock.
 * This is the inverse of the validatedAt pattern, where the timestamp is operational
 * rather than user-supplied (see ValidateClinicalContributionHandler).
 *
 * WHY the Handler does not know which events the Aggregate recorded:
 * The Handler calls pullPendingEvents() and passes the result to the collector without
 * inspecting the events. The events' meaning and routing are Infrastructure and Domain
 * concerns. The Handler's only obligation is collection and propagation (SA-005 §13.3).
 *
 * Depends on: ClinicalContributionRepositoryPort, DomainEventCollectorPort.
 * Never depends on: Read Model Ports, Infrastructure implementations, any business rule.
 */
final class ApproveClinicalContributionHandler
{
    public function __construct(
        private readonly ClinicalContributionRepositoryPort $repository,
        private readonly DomainEventCollectorPort $eventCollector,
    ) {}

    public function __invoke(ApproveClinicalContribution $command): void
    {
        $contribution = $this->repository->retrieve($command->clinicalContributionId);

        $contribution->approve($command->approvingPractitionerId, $command->approvedAt);

        $this->repository->persist($contribution);
        $this->eventCollector->collect($contribution->pullPendingEvents());
    }
}
