<?php

declare(strict_types=1);

namespace App\Platforms\Clinical\Application\CommandHandler;

use App\Platforms\Clinical\Application\Command\ApproveClinicalContribution;
use App\Platforms\Clinical\Application\Port\ClinicalContributionRepositoryPort;

/**
 * Command Handler — UC-003: Approve Clinical Contribution.
 *
 * Single responsibility: execute the Approve use case within exactly one transaction
 * boundary owned by the Application Runtime (SA-007 §6.2, SA-005 D-003).
 *
 * Execution sequence (ADR-SA-013 §6.4):
 *  1. Runtime opens transaction.
 *  2. Handler retrieves ClinicalContribution via repository.retrieve().
 *  3. Handler calls aggregate.approve(approvingPractitionerId, approvedAt).
 *  4. Aggregate enforces BI-005 (status must be Validated) — throws if violated.
 *  5. Aggregate enforces BI-007 (approver ≠ contributor) — throws if violated.
 *  6. Aggregate records ClinicalContributionApproved and marks contribution immutable.
 *  7. Handler calls repository.persist() — updated aggregate state written within transaction.
 *  8. Repository calls collector.collect(contribution.releaseDomainEvents()) — events held.
 *  9. DomainEventPublisherMiddleware flushes, creates EventEnvelopes, writes to Outbox.
 * 10. doctrine_transaction COMMIT — aggregate write + Outbox write are atomic.
 *
 * WHY the Handler does not check BI-005 or BI-007 before calling approve():
 * Business invariant enforcement belongs exclusively to the Aggregate (PR-002 D-017).
 *
 * WHY approvedAt is carried in the Command rather than generated by the Handler:
 * The approval timestamp is a caller-supplied business input — the moment the Approving
 * Practitioner formally endorsed the contribution.
 *
 * WHY the Handler no longer injects DomainEventCollectorPort:
 * Per ADR-SA-013 R-006 and R-010, the Repository is the sole caller of collect().
 *
 * Depends on: ClinicalContributionRepositoryPort.
 * Never depends on: Read Model Ports, Infrastructure implementations, any business rule.
 */
final class ApproveClinicalContributionHandler
{
    public function __construct(
        private readonly ClinicalContributionRepositoryPort $repository,
    ) {}

    public function __invoke(ApproveClinicalContribution $command): void
    {
        $contribution = $this->repository->retrieve($command->clinicalContributionId);

        $contribution->approve($command->approvingPractitionerId, $command->approvedAt);

        $this->repository->persist($contribution);
    }
}
